name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hi!
    runs-on: ubuntu-latest
    permissions: none
      issues: write
      pull-requests: write
    steps: Just update it.
    - uses: actions/first-interaction@v1
      with: none
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting!'
        pr-message: 'Thanks for submitting!'
